# Generated by Django 6.0.3 on 2026-03-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="(Opcional)",
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensaje/Propuesta")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
