# Generated by Django 6.0.3 on 2026-03-21 03:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
            },
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="(Opcional)",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Teléfono",
            ),
        ),
    ]
