# Generated by Django 6.0.3 on 2026-03-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="Nombre/s"),
                ),
                ("last_name", models.CharField(max_length=30, verbose_name="Apellido")),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Rol (ej. Fotógrafo/a, Maquillador/a, etc)",
                    ),
                ),
                (
                    "contact",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Contacto (URL ej. Instagram, Portfolio, etc)",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        default="O",
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaboradora",
                "verbose_name_plural": "Colaboradores",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collections",
                        to="portfolio.collaborator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colección",
                "verbose_name_plural": "Colecciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        upload_to="portfolio/images/",
                        verbose_name="Archivo de la Imágen",
                        width_field="width",
                    ),
                ),
                ("width", models.IntegerField(editable=False, null=True)),
                ("height", models.IntegerField(editable=False, null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "captured_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Captura"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pictures",
                        to="portfolio.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto",
                "verbose_name_plural": "Fotos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        upload_to="portfolio/videos/", verbose_name="Archivo del Video"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="HH:MM:SS",
                        null=True,
                        verbose_name="Duración",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Subida"
                    ),
                ),
                (
                    "captured_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Captura"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="portfolio.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
