# Generated by Django 6.0.3 on 2026-03-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
