# Generated by Django 6.0.3 on 2026-03-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_collection_cover_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_file",
            new_name="file",
        ),
        migrations.AddField(
            model_name="video",
            name="id_collection",
            field=models.CharField(
                db_index=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
    ]
