# Generated by Django 6.0.3 on 2026-03-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_collection_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["-captured_at"],
                "verbose_name": "Colección",
                "verbose_name_plural": "Colecciones",
            },
        ),
        migrations.AlterModelOptions(
            name="picture",
            options={
                "ordering": ["-captured_at"],
                "verbose_name": "Foto",
                "verbose_name_plural": "Fotos",
            },
        ),
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["-captured_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="captured_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de captura"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Fecha de publicación"
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="captured_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de captura"
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de publicación"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="captured_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de captura"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de publicación"
            ),
        ),
    ]
