# Generated by Django 6.0.3 on 2026-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_video_file_video_file_video_id_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="height",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="width",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
