# Generated by Django 6.0.3 on 2026-03-19 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_collection_options_alter_picture_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collaborator",
            options={
                "verbose_name": "Colaborador/a",
                "verbose_name_plural": "Colaboradores",
            },
        ),
    ]
