# Generated by Django 6.0.3 on 2026-03-21 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_video_height_video_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="contact",
            field=models.URLField(
                blank=True,
                help_text="(URL ej. Instagram, Portfolio, etc)",
                null=True,
                verbose_name="Contacto",
            ),
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Apellido/s"),
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="(ej. Fotógrafo/a, Maquillador/a, etc)",
                max_length=100,
                null=True,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                to="portfolio.collaborator",
                verbose_name="Colaboladores",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover",
                to="portfolio.picture",
                verbose_name="Portada",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="cover_video",
            field=models.ForeignKey(
                blank=True,
                help_text="(Previsualización de video como portada)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="portfolio.video",
                verbose_name="Portada Animada",
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pictures",
                to="portfolio.collection",
                verbose_name="Album de Pertenencia",
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="height",
            field=models.IntegerField(
                editable=False, help_text="px", null=True, verbose_name="Alto"
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="id_collection",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="width",
            field=models.IntegerField(
                editable=False, help_text="px", null=True, verbose_name="Ancho"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="portfolio.collection",
                verbose_name="Album de Pertenencia",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="height",
            field=models.IntegerField(
                editable=False, help_text="px", null=True, verbose_name="Alto"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id_collection",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="width",
            field=models.IntegerField(
                editable=False, help_text="px", null=True, verbose_name="Ancho"
            ),
        ),
    ]
