# Generated by Django 6.0.3 on 2026-03-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_collaborator_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Destacar"),
        ),
    ]
