# Generated by Django 6.0.3 on 2026-03-30 20:55

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_collaborator_contact_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={},
        ),
        migrations.RemoveField(
            model_name="video",
            name="duration",
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Imágen"), ("video", "Video")],
                        default="image",
                        max_length=10,
                        verbose_name="Tipo de Archivo",
                    ),
                ),
                (
                    "image_file",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="WEBP",
                        height_field="height",
                        keep_meta=True,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[2048, 2048],
                        upload_to="portfolio/media/images/",
                        verbose_name="Archivo de la Imágen",
                        width_field="width",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/media/videos/",
                        verbose_name="Archivo del Video",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="HH:MM:SS",
                        null=True,
                        verbose_name="Duración",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/media/thumbnails/",
                        verbose_name="Miniatura del Video",
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        editable=False, help_text="px", null=True, verbose_name="Ancho"
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        editable=False, help_text="px", null=True, verbose_name="Alto"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de publicación"
                    ),
                ),
                (
                    "captured_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de captura"
                    ),
                ),
                (
                    "id_collection",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_items",
                        to="portfolio.collection",
                        verbose_name="Album de Pertenencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Multimedia",
                "verbose_name_plural": "Items Multimedias",
                "ordering": ["order"],
            },
        ),
    ]
