# Generated by Django 6.0.3 on 2026-03-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_collection_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="(Mostrar en Home)", verbose_name="Destacar"
            ),
        ),
    ]
