# Generated by Django 6.0.3 on 2026-03-30 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_video_options_remove_video_duration_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "image"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_for",
                to="portfolio.media",
                verbose_name="Portada",
            ),
        ),
        migrations.RemoveField(
            model_name="video",
            name="collection",
        ),
        migrations.AlterField(
            model_name="collection",
            name="cover_video",
            field=models.ForeignKey(
                blank=True,
                help_text="(Previsualización de video como portada)",
                limit_choices_to={"type": "video"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_video_for",
                to="portfolio.media",
                verbose_name="Portada Animada",
            ),
        ),
        migrations.AlterModelOptions(
            name="media",
            options={
                "ordering": ["order"],
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
            },
        ),
        migrations.DeleteModel(
            name="Picture",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
