# Generated by Django 6.0.3 on 2026-03-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_collection_cover_remove_video_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio/media/thumbnails/",
                verbose_name="Miniatura",
            ),
        ),
    ]
