# Generated by Django 6.0.3 on 2026-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_media_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["-captured_at", "featured_order"],
                "verbose_name": "Colección",
                "verbose_name_plural": "Colecciones",
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="featured_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
