# Generated by Django 6.0.3 on 2026-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_collection_options_collection_featured_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["featured_order"],
                "verbose_name": "Colección",
                "verbose_name_plural": "Colecciones",
            },
        ),
        migrations.AlterField(
            model_name="media",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="(En la sección de destacados)",
                verbose_name="Orden",
            ),
        ),
    ]
