# Generated by Django 6.0.3 on 2026-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_collection_options_alter_media_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="featured_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="(En la sección de destacados)",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="(dentro de su álbum)", verbose_name="Orden"
            ),
        ),
    ]
