# Generated by Django 6.0.3 on 2026-05-21 14:28

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_collection_featured_order_alter_media_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="medium_file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio/media/medium/",
                verbose_name="Imágen Mediana",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="image_file",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                height_field="height",
                keep_meta=True,
                null=True,
                quality=90,
                scale=None,
                size=[2048, 2048],
                upload_to="portfolio/media/images/",
                verbose_name="Archivo de la Imágen",
                width_field="width",
            ),
        ),
    ]
